name: Dependency Checker

on: 
  push:
    branches: [main]

jobs: 
  job1:
    name: JOB1-
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        run: |
          pwd
          ls -ltr
          hostname
      - name: step2 - checkout
        uses: actions/checkout@v7.0.0
      - name: step-3
        run: | 
          pwd
          ls -ltr
          hostname
