name: Dependency Checker

on:
  push:
    branches:
      - dev
      - 'feature-*'
      - main
  pull_request:
    branches:
      - main
      
jobs:
  job1:
    name: Job1 - Create Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: |
          pwd
          ls -ltr
          hostname

      - name: step2 - Checkout
        uses: actions/checkout@v4

      - name: Create Files
        run: |
          echo `pwd` > myfile.txt
          mkdir -p artifacts
          echo `ls -ltr` > artifacts/lists.txt
          echo `hostname` > artifacts/hostname.txt

      - name: Verify Created Files
        run: |
          ls -R
      - name: Upload Single File
        uses: actions/upload-artifact@v4
        with:
          name: single_file
          path: ./myfile.txt

  job2:
    name: Job2 - Download Artifacts
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Pre-Download Check
        run: |
          pwd
          ls -ltr

      - name: Download Single File Artifact
        uses: actions/download-artifact@v4
        with:
          name: single_file
      - name: Verify Downloaded Files
        run: |
          echo "Downloaded contents:"
          ls -ltr
          echo "Contents of myfile.txt:"
          cat myfile.txt
      - name: PR demo for fail
        run: exit 1

  
