name: Dependency Checker

on: 
  push:
    branches: [main]

jobs: 
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up python env
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip

  check-node:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-verison: 18